### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by user-grinch** [user-grinch/PyLoaderSA#1]
### Rewrite (BREAKING CHANGE)
*Attempt to reimagine the codebase from the ground up*

- [ ] Redo the runtime modules
- [ ] Decrease the function calling hierarchy as much as possible
- [x] Remove plugin-sdk backend dependency
- [x] Enable GitHub actions for daily builds
- [x] Implement file watcher (load, unload, reload)

**Comment by darylreznov** [comment]
Great work!
